var jsoneg = [
/* acad */
{"r_basicprofile":["Vice President","Computer Software"],
"duration":1.2,
"positions":[{"Business", "MBA", "skills":["Strategy", "Finance", "Marketing", "Business Planning"]}, 
             {"Consulting", "Senior Analyst", "skills": ["Market analysis", "Cross function team management"]}, 
			 {"Mid size company", "Director", "skills": ["Competitive analysis", "Corporate development"]}, 
			 {"Small business", "Vice President", "skills": ["Strategic Partnerships", "Acquisition Integration"]}],
},
{"r_basicprofile" : ["Assistant Professor","Research"],
"duration":1.5,
"positions":[{"Research", "Doctoral Candidate", "skills":["Computer Architecture", "Compilers", "Algorithms", "Simulations", "Graduate Research"]},
			 {"Research", "Post Doctoral Candidate", "skills": ["Independent Research", "Experiment Design"]}, 
			 {"Industry Research", "Senior Research Scientist", "skills":["Analytical Modeling", "Industry Collaboration", "Integration of Research idea to product"]}, 
			 {"Academia", "Associate Professor", "skills": ["Research leader", "Teaching", "Technical consultant"]}],
},
/* disrupt */
{"r_basicprofile":["Principal Architect","Computer Hardware"],
"duration":1.5,
"positions":[{"Computer Hardware", "Lead Architect", "skills":["Architecture Design", "Architectural Exploration", "Low power design", "Programming model"]}, 
             {"Computer Hardware", "Chip Architect", "skills": ["Competitive analysis", "Project management", "Cross unit team schedule management"]}, 
             {"Computer Hardware", "Senior Architect", "skills": ["Compiler analysis", "Unit Performance Analysis", "Architecture decision validation studies"]}], 
},

/* mgmt */
{"r_basicprofile":["Vice President","Computer Software"],
"duration":1.5,
"positions":[{"Business", "MBA", "skills":["Strategy", "Finance", "Marketing", "Business Planning"]}, 
             {"Consulting", "Senior Analyst", "skills": ["Market analysis", "Cross function team management"]}, 
			 {"Mid size company", "Director", "skills": ["Competitive analysis", "Corporate development"]}, 
			 {"Small business", "Vice President", "skills": ["Strategic Partnerships", "Acquisition Integration"]}],
},
/* patent */
{"r_basicprofile":["Intellectual Property Attorney","Legal Services"],
"duration":1.5,
"positions":[{"Law", "JD Intellectual Property Law", "skills":[ "Patent Law", "Patent Litigation", "Patent Prosecution", "Contract Drafting"]},
             {"Legal Services", "Associate", "skills": ["Intellectual Property Transactions and Licensing", "Litigation Drafting", "Cross function team management"]}, 
             {"Legal Consulting", "Patent Consultant", "skills": ["Patent procurement", "Open Source Licensing", "Strategic creation procurement", "Patent enforcement"]}], 
},
/* sw */
{"r_basicprofile":["CEO","Computer Software"],
"duration":1.5,
"positions":[{"Computer Software", "Lead Software Engineer", "skills":["Full-stack engineer", ""]}, 
             {"Computer Software", "Chip Architect", "skills": ["Competitive analysis", "Project management", "Cross unit team schedule management"]}, 
             {"Computer Software", "Senior Architect", "skills": ["Compiler analysis", "Unit Performance Analysis", "Architecture decision validation studies"]}], 
},
];
